spring.application.name=task

# DataSource connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/safe_task
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:f9K2xP7vLq91sT4YbW3nZmR8uH5cDxQa}
